<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AppComercial.Api\AppComercial.Api.csproj" />
    <ProjectReference Include="..\AppComercial.Infrastructure\AppComercial.Infrastructure.csproj" />
    <ProjectReference Include="..\AppComercial.Application\AppComercial.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.5" />
  </ItemGroup>

</Project>
